package service

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/mhsanaei/3x-ui/v2/backend"
	"github.com/mhsanaei/3x-ui/v2/database"
	"github.com/mhsanaei/3x-ui/v2/database/model"
	"github.com/mhsanaei/3x-ui/v2/logger"
)

// The bundled strongSwan charon is a SINGLE shared daemon (procMgr key ikev2ProcName)
// that serves BOTH IKEv2 (per-inbound conf.d/ikev2-<id>.conf) and, since we unified the
// IPsec layer, L2TP/IPsec IKEv1 transport (conf.d/l2tp.conf). It owns UDP 500/4500 for
// both, which removes the old charon-vs-pluto (libreswan) port collision. This file holds
// the charon lifecycle both the ikev2 and l2tp services drive; swanctl.conf's
// `include conf.d/*.conf` loads every connection with one `swanctl --load-all`.

// charonBin / swanctlBin resolve the bundled launchers (or a host binary from PATH).
func charonBin() string {
	if p := backend.StrongswanBinPath("charon"); p != "" {
		return p
	}
	return "charon"
}

func swanctlBin() string {
	if p := backend.StrongswanBinPath("swanctl"); p != "" {
		return p
	}
	return "swanctl"
}

// charonNeeded reports whether the shared charon should be running: true when any
// enabled IKEv2 inbound exists, or any enabled L2TP inbound has IPsec enabled.
func charonNeeded() bool {
	db := database.GetDB()
	if db == nil {
		return false
	}
	var ikev2Count int64
	db.Model(&model.Inbound{}).Where("protocol = ? AND enable = ?", "ikev2", true).Count(&ikev2Count)
	if ikev2Count > 0 {
		return true
	}
	var l2tps []*model.Inbound
	db.Model(&model.Inbound{}).Where("protocol = ? AND enable = ?", "l2tp", true).Find(&l2tps)
	for _, ib := range l2tps {
		if l2tpInboundHasIpsec(ib) {
			return true
		}
	}
	return false
}

// l2tpInboundHasIpsec reports whether an l2tp inbound has IPsec enabled (ipsecEnable
// defaults to true when the key is absent, matching the l2tp settings model).
func l2tpInboundHasIpsec(inbound *model.Inbound) bool {
	if inbound == nil {
		return false
	}
	var st struct {
		IpsecEnable *bool `json:"ipsecEnable"`
	}
	_ = json.Unmarshal([]byte(inbound.Settings), &st)
	return st.IpsecEnable == nil || *st.IpsecEnable
}

// charonDNS returns the DNS servers to advertise (IKEv2 pools use them; L2TP gets DNS
// from PPP, so this only matters for ikev2). Falls back to public resolvers.
func charonDNS() (string, string) {
	dns1, dns2 := "8.8.8.8", "8.8.4.4"
	db := database.GetDB()
	if db == nil {
		return dns1, dns2
	}
	var ikev2s []*model.Inbound
	db.Model(&model.Inbound{}).Where("protocol = ? AND enable = ?", "ikev2", true).Find(&ikev2s)
	for _, ib := range ikev2s {
		var st struct {
			Dns1 string `json:"dns1"`
			Dns2 string `json:"dns2"`
		}
		if json.Unmarshal([]byte(ib.Settings), &st) == nil {
			if st.Dns1 != "" {
				dns1 = st.Dns1
			}
			if st.Dns2 != "" {
				dns2 = st.Dns2
			}
			break
		}
	}
	return dns1, dns2
}

// writeCharonConf writes /etc/strongswan.conf (shared charon config incl. the eap-radius
// plugin for IKEv2 EAP-MSCHAPv2, harmless to L2TP) + /etc/swanctl/swanctl.conf (which
// includes every conf.d/*.conf: ikev2-<id>.conf and l2tp.conf). Written whenever charon
// is needed by either protocol, so an L2TP-only box also gets a valid config to boot on.
func writeCharonConf() error {
	dns1, dns2 := charonDNS()
	var settingService SettingService
	radiusSecret, _ := settingService.GetRadiusSecret()

	_ = os.MkdirAll(ikev2ConfigRoot, 0755)

	var b strings.Builder
	b.WriteString("# Auto-generated by vpn-ui (shared charon) - do not edit\n")
	b.WriteString("charon {\n")
	b.WriteString("    load_modular = yes\n")
	// `never` (not `no`): ignore INITIAL_CONTACT so multiple devices per account coexist;
	// the panel RADIUS governs the K limit for IKEv2.
	b.WriteString("    uniqueids = never\n")
	// Stay root: the bundled charon (Alpine build) would setuid to a nonexistent `ipsec`
	// user and abort. The panel runs as root and needs CAP_NET_ADMIN for XFRM anyway.
	b.WriteString("    user = root\n")
	b.WriteString("    group = root\n")
	// We own routing via nftables TPROXY; charon must NOT install a 0.0.0.0/0 route. This
	// only suppresses route installation, not the transport/tunnel XFRM policies.
	b.WriteString("    install_routes = no\n")
	b.WriteString("    filelog {\n")
	b.WriteString("        stderr {\n")
	b.WriteString("            default = 1\n")
	b.WriteString("            ike_name = yes\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("    plugins {\n")
	b.WriteString(fmt.Sprintf("        include %s/charon/*.conf\n", backend.StrongswanDefaultConfDir))
	b.WriteString("        eap-radius {\n")
	b.WriteString("            accounting = yes\n")
	b.WriteString("            accounting_interval = 300\n")
	b.WriteString("            servers {\n")
	b.WriteString("                vpnui {\n")
	b.WriteString("                    address = 127.0.0.1\n")
	b.WriteString(fmt.Sprintf("                    secret = %s\n", radiusSecret))
	b.WriteString("                    auth_port = 1812\n")
	b.WriteString("                    acct_port = 1813\n")
	b.WriteString("                    nas_identifier = ikev2\n")
	b.WriteString("                }\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n")
	b.WriteString("        attr {\n")
	b.WriteString(fmt.Sprintf("            dns = %s, %s\n", dns1, dns2))
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	if err := os.WriteFile("/etc/strongswan.conf", []byte(b.String()), 0600); err != nil {
		return fmt.Errorf("write /etc/strongswan.conf: %w", err)
	}

	_ = os.MkdirAll(swanctlConfDir, 0755)
	_ = os.MkdirAll(swanctlX509, 0755)
	_ = os.MkdirAll(swanctlX509CA, 0755)
	_ = os.MkdirAll(swanctlPrivate, 0700)
	return os.WriteFile(swanctlDir+"/swanctl.conf", []byte("include conf.d/*.conf\n"), 0600)
}

// ensureCharonRunning extracts/links the strongswan bundle and starts the shared charon
// (procMgr key ikev2ProcName) if it isn't already up, waiting for its vici socket.
// Idempotent; never drops live SAs when charon is already running.
func ensureCharonRunning() error {
	// Extract the bundle only if absent: re-extracting under a running charon overwrites
	// mmap'd .so files and SEGFAULTs it. The symlink is idempotent + always ensured.
	if !backend.StrongswanBundleReady() {
		if err := backend.ExtractStrongswanBundle(); err != nil {
			logger.Warning("charon: extract strongswan bundle:", err)
		}
	}
	if err := backend.LinkStrongswanIpsecDir(); err != nil {
		logger.Warning("charon: link strongswan ipsec dir:", err)
	}
	if !procMgr.IsRunning(ikev2ProcName) {
		_ = os.MkdirAll("/var/run", 0755)
		if err := procMgr.Start(ikev2ProcName, charonBin(), nil, nil, ikev2ConfigRoot); err != nil {
			return fmt.Errorf("start charon: %w", err)
		}
		if !waitForPath(viciSocket, 10*time.Second) {
			logger.Warning("charon: vici socket never appeared at", viciSocket)
		}
	}
	return nil
}

// reloadCharon (re)loads all swanctl conf.d connections/creds/pools into the running
// charon without dropping live SAs.
func reloadCharon() error {
	// Right after charon starts, its vici socket file can exist before charon actually
	// accepts connections (plugins still initializing), so a single --load-all can fail
	// with "Connection refused". On an ikev2+l2tp box the other protocol's later syncCharon
	// covers this, but an l2tp-only (or ikev2-only) box gets one shot, so retry briefly on
	// a vici connection error. A genuine config error (not a connect failure) breaks early.
	var out []byte
	var err error
	for attempt := 0; attempt < 6; attempt++ {
		out, err = exec.Command(swanctlBin(), "--load-all").CombinedOutput()
		if err == nil {
			return nil
		}
		s := string(out)
		if !strings.Contains(s, "Connection refused") && !strings.Contains(s, "connecting to") {
			break
		}
		time.Sleep(time.Second)
	}
	logger.Warning("charon: swanctl --load-all:", err, strings.TrimSpace(string(out)))
	return nil
}

// stopCharon stops the shared charon process.
func stopCharon() error {
	return procMgr.Stop(ikev2ProcName)
}

// syncCharon is the shared entrypoint both the ikev2 and l2tp services call after
// writing their own conf.d files. It starts (or stops) the one charon based on whether
// either protocol still needs it, and reloads all connections. Because it is keyed on the
// shared ikev2ProcName, ikev2 and l2tp cooperate: whichever runs last leaves charon in the
// right state, and `swanctl --load-all` merges both sets of conf.d files.
func syncCharon() error {
	if !charonNeeded() {
		return stopCharon()
	}
	if err := writeCharonConf(); err != nil {
		return err
	}
	if err := ensureCharonRunning(); err != nil {
		return err
	}
	return reloadCharon()
}
